### ISSUE TITLE
Select all files in folder / asterisk select is not possible

### ISSUE THREAD

**Issue by pschonmann** [XhmikosR/jpegoptim-windows#1]
```
d:\TEMP\>jpegoptim.exe *.jpg
jpegoptim: skipping special file: *.jpg

d:\TEMP\>jpegoptim2.exe ./
jpegoptim: skipping directory: ./
```

In version 1.4.4 it was possible optimize *.jpg with no problem.

**Comment by XhmikosR** [comment]
Wrong repo. You should report this upstream.

**Comment by XhmikosR** [comment]
@pschonmann: it was an issue with the Windows build, I didn't expect this to happen.

https://github.com/XhmikosR/jpegoptim-windows/releases/tag/1.4.6-rel4

**Comment by RoyiAvital** [comment]
Does it support compressing PNG to JPEG or just JPEG?

**Comment by XhmikosR** [comment]
This is just a Windows build of jpegoptim. It's whatever jpegoptim supports.

**Comment by RoyiAvital** [comment]
Seems it doesn't. It works only on JPEG.
