### ISSUE TITLE
Parallel processing support in 1.5.1?

### ISSUE THREAD

**Issue by dmitry-brok** [XhmikosR/jpegoptim-windows#12]
Should this parallel processing work? Even no mention in help output --help

AFAIK this -w<MAX> option works since version 1.5.0. 
_>>Parallel processing support added. Use option -w max or --workers=max to enable._

I built Timo's jpegoptim under Ubuntu and the -w worked just fine
This Windows build seems to have no this option enabled
I am correct?

I really need this parallel processing under Windows... Is there a way to get it?

Thank you

**Comment by XhmikosR** [comment]
It's not implemented for Windows AFAICT.
