### ISSUE TITLE
Error if path to solution contains whitespaces

### ISSUE THREAD

**Issue by jialiang** [XhmikosR/jpegoptim-windows#6]
Hi just want to mention that the build breaks if the path where the solution is at contains white spaces:

e.g. `C:\Users\Name Name\...`

It gives a multiple input files error when trying to run NASM.

in `src\nasm.targets`: line 52:

`OutputFormat="%(NASM.OutputFormat)"` needs to be changed to
`OutputFormat="&quot;%(NASM.OutputFormat)&quot;"`

**Comment by XhmikosR** [comment]
Never use spaces in paths as the rule of thumb...

**Comment by XhmikosR** [comment]
Fixed in https://github.com/XhmikosR/jpegoptim-windows/commit/8d9d419880e5b2fff79765772f043eb317d0b760
